version: '3.8'

services:
  oss-sync-tool-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: oss-sync-tool-server
    container_name: oss-sync-tool-server
    ports:
      - "8965:8965"
    environment:
      - NODE_ENV=production
      - PORT=8965
      # 数据库配置
      - DB_HOST=数据库IP
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=数据库密码
      - DB_DATABASE=osstool
      # 数据文件保存路径（容器中的）
      - WORKSPACE_BASE_DIR=/home/node/oss-workspace
      # 阿里云OSS配置
      - OSS_ACCESS_KEY_ID=your_access_key_id
      - OSS_ACCESS_KEY_SECRET=your_access_key_secret
    volumes:
      # 数据文件保存路径（宿主机中的）
      - /root/oss-workspace:/home/node/oss-workspace:rw
    restart: unless-stopped
    networks:
      - oss-sync-network
    user: "node"

networks:
  oss-sync-network:
    driver: bridge 